### ISSUE TITLE
Coupla typos in Readme.md

### ISSUE THREAD

**Issue by sammyjava** [molpopgen/pecnv#7]
Trying to wrap my head around the extra output fields from teclust, I think you have two errors:
```
minus (int) = the number of read pairs on the right-hand side/minus strand of the event. In total, columns 2 and 3 are the "coverage" in support of this event
```
That should read 'columns 1 and 2.'

Also in the final line you repeat 'pfirst' and 'plast' when you mean 'mfirst' and 'mlast' since it's the minus strand.

**Comment by molpopgen** [comment]
Fixed by https://github.com/molpopgen/pecnv/commit/877fd1451f99398554bddeeaf2952ef754cfccf1
