### ISSUE TITLE
Error parsing xtra field data on line 91 of teclust_phrapify.cc

### ISSUE THREAD

**Issue by sammyjava** [molpopgen/pecnv#8]
I've run a modified version of run_TEtest_data.sh to use my own data rather than the downloaded example data, and teclust runs fine until the -p option kicks in, at which it throws the above error and puts nothing in /phrapdir. I'd like to get the fastas to assemble contigs with phrap or another tool. I don't actually have phrap yet, but I don't think that's the issue in teclust_phrapify.cc. Here's the output:
```
sam> ./run_pecnv.sh
Input file name is set to 'infile'
Reference file name is set to 'AGPv3.fa'
bwa is /usr/local/bin/bwa
samtools is /usr/bin/samtools
pecnv is /usr/local/bin/pecnv
Rscript is /usr/bin/Rscript
pecnv_insert_qtile is /usr/local/bin/pecnv_insert_qtile
Making output directory pecnv_output
Using default ulimit
clustering div
clustering par
clustering ul
Error parsing xtra field data on line 91 of teclust_phrapify.cc
parallel is /usr/bin/parallel
which: no phrap in (/usr/lib/jvm/java/bin:/usr/local/ncbi/sra-tools/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
Cannot find phrap in your user's PATH
sam>
```
And here's the script I'm running (this is actually on an eight-core machine, so the defaults are correct):
```
sam> cat run_pecnv.sh 
#!/usr/bin/env bash

CPU=4
PHRAPCPU=8

command_exists () {
    type "$1" &> /dev/null ;
}

##Run the pecnv pipeline
pecnv.sh  -i infile -r AGPv3.fa -c $CPU

##Get the 99th quantile of the insert size distribution
u99=`pecnv_insert_qtile pecnv_output/pecnv_bamfile.mdist.gz 0.99`

##Run teclust
pecnv teclust -b pecnv_output/pecnv_bamfile_sorted.bam -t TE_18-Dec-2014.blastn.positions.bed -o teclust_output.gz -u pecnv_output/pecnv_bamfile.um_u.csv.gz -m pecnv_output/pecnv_bamfile.um_m.csv.gz -i $u99 -p phrapdir

##If we have the right stuff on the system, assemble in parallel using phrap
CANASSEMBLE=1
for needed in parallel phrap
do
    PM=`which $needed`
    if [ -z ${PM} ]
    then
        >&2 echo "Cannot find $needed in your user's PATH"
        CANASSEMBLE=0
    else
        echo "$needed is $PM"
    fi
done

if [ $CANASSEMBLE -eq 1 ]
then
    find phrapdir -name "*.fasta" | parallel --jobs $PHRAPCPU --timeout 300 "phrap {} -vector_bound 0 -forcelevel 10 -minscore 10 -minmatch 10 -new_ace 2> {}.stderr > {}.stdout"
fi
sam> 
```
Appreciate any tips!

**Comment by molpopgen** [comment]
It would be informative if you could run the test data and let me know what happens with that.

**Comment by molpopgen** [comment]
Would it be possible for you to make the teclust_output.gz file available for me to look at?

**Comment by sammyjava** [comment]
Sure, I'll run_TEtest_data.sh. In the meantime, how would you like me to get my teclust_output.gz to you? I don't see a way of attaching it here. Here's the top buncha lines, though:
```
sam> zcat teclust_output.gz | head
1       4950    5101    .       -1      -1 chr1_event0  1.17609 +       -       15      0       6524    0       -1      -1
1       6358    6415    .       -1      -1 chr1_event1  0.60206 +       -       4       0       5116    0       -1      -1
.       -1      -1      1       6358    6446    chr1_event2     1.81954 +       -       0       66      -1      -1      -1      0
1       7764    7765    .       -1      -1 chr1_event3  0       +       -       1       0       3710    0       -1      -1
1       9520    9521    .       -1      -1 chr1_event4  0       +       -       1       0       1954    0       -1      -1
.       -1      -1      1       143739  143740  chr1_event5     0       +       -       0       1       -1      -1      0       1
.       -1      -1      1       215674  215675  chr1_event6     0       +       -       0       1       -1      -1      9041    0
.       -1      -1      1       262779  262780  chr1_event7     0       +       -       0       1       -1      -1      582     0
1       1193152 1193153 .       -1      -1 chr1_event8  0       +       -       1       0       2006    0       -1      -1
1       1961021 1961086 1       1961086 1961087 chr1_event9     0.60206 +       -       3       1       12100   0       2152    0
sam>
```

**Comment by molpopgen** [comment]
You can email it to me -- my email address at UCI is easy to find via google, or use whatever sort of file-sharing cloud thing you like, and provide me a link (dropbox, google drive,etc.).  The file is typically small and the error is appearing in the function that processes it.

**Comment by molpopgen** [comment]
I'm re-running the same test script on my server, too, just to double-check...

**Comment by molpopgen** [comment]
You can hold off on running the test script--I think I seen an issue.  I have a call to strtok that looks out-of-sync with what the record-separating character actually is.  I'll know more by end of day.

**Comment by sammyjava** [comment]
Cool, thanks! I presume you don't need my teclust_output.gz since you're on it. BTW I sent you an email a few days ago asking about breakpoints, but I hadn't seen Supplementary Figure 1 which is what I needed (ooops). I was confused about getting from step 4 to step 5 on that figure, the answer is use the -p option to get the FASTAs for phrap, which is where we are now. Much appreciated!

**Comment by molpopgen** [comment]
Yeah--no need to send the file.  I've confirmed the issue on my end.  I didn't get an email, or at least cannot find one now in my inbox...

> On Jan 22, 2015, at 11:27 AM, Sam Hokin <notifications@github.com> wrote:
> 
> Cool, thanks! I presume you don't need my teclust_output.gz since you're on it. BTW I sent you an email a few days ago asking about breakpoints, but I hadn't seen Supplementary Figure 1 which is what I needed (ooops). I was confused about getting from step 4 to step 5 on that figure, the answer is use the -p option to get the FASTAs for phrap, which is where we are now. Much appreciated!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

___________________________
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
University of California, Irvine
http://www.molpopgen.org

**Comment by molpopgen** [comment]
This is fixed on my system by commit https://github.com/molpopgen/pecnv/commit/8ddd8ae7c6695823914bbe9700385a993af732ba, and the new release 0.1.6-bugfix1 contains the fix.

Let me know if this solves it on your system.

**Comment by sammyjava** [comment]
Yup, thanks!!! No errors.
```
sam> ls phrapdir | head
10.126155220.126155242.left.fasta
10.126155220.126155242.left.fasta.qual
10.126155471.126155523.right.fasta
10.126155471.126155523.right.fasta.qual
10.126155934.126155990.left.fasta
10.126155934.126155990.left.fasta.qual
10.126156218.126156309.right.fasta
10.126156218.126156309.right.fasta.qual
10.128547496.128547574.left.fasta
10.128547496.128547574.left.fasta.qual
sam> 
```
